In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn

In [7]:
# Loading the Train and Test Sets

Training_data = pd.read_csv('Train_maskedv2.csv')
Testing_data = pd.read_csv('Test_maskedv2.csv')
full_data = [Training_data, Testing_data]

Training_data.head()

,ward,total_households,total_individuals,target_pct_vunerable,dw_00,dw_01,dw_02,dw_03,dw_04,dw_05,...,lan_11,lan_12,lan_13,lan_14,pg_00,pg_01,pg_02,pg_03,pg_04,lgt_00
0,9D9BEUB,13569.97801,39024.03083,1.739801,0.354806,0.004781,0.170498,0.007861,0.006796,0.023082,...,0.001723,0.027796,0,0.026727,0.524666,0.041460,0.394550,0.029031,0.010292,0.599259
1,RERH3XM,13593.88256,32879.94646,1.993381,0.262140,0.002066,0.077669,0.000597,0.000977,0.003759,...,0.041982,0.021312,0,0.015754,0.993900,0.001829,0.000854,0.000586,0.002832,0.699136
2,GJWA3BO,2698.30050,8261.71093,0.038340,0.728101,0.002292,0.051663,0.008209,0.001444,0.005089,...,0.014786,0.005827,0,0.049384,0.990007,0.003582,0.002546,0.003201,0.000663,0.972315
3,GW6VRB7,1965.96698,9069.77694,7.411006,0.613206,0.138127,0.004999,0.002704,0.000000,0.002788,...,0.003087,0.003136,0,0.013562,0.928682,0.004464,0.009854,0.054701,0.002299,0.735333
4,CN9JZJC,1852.07821,9908.84404,8.223907,0.797462,0.120830,0.060677,0.001155,0.001042,0.000508,...,0.000117,0.001471,0,0.000000,0.994072,0.000476,0.004033,0.000704,0.000714,0.646964

In [8]:
#print (Training_data.info())

In [9]:
#Training_data.isnull()

In [14]:
#Training_data.drop(['ward'],inplace=True,axis=1)
#Testing_data.drop(['ward'],inplace=True,axis=1)

#converting columns to float
Training_data[1:19] = Training_data[1:19].astype(float)
Testing_data[1:19] = Testing_data[1:19].astype(float)

In [15]:

Training_data.head(2)

,total_households,total_individuals,target_pct_vunerable,dw_00,dw_01,dw_02,dw_03,dw_04,dw_05,dw_06,...,lan_11,lan_12,lan_13,lan_14,pg_00,pg_01,pg_02,pg_03,pg_04,lgt_00
0,13569.97801,39024.03083,1.739801,0.354806,0.004781,0.170498,0.007861,0.006796,0.023082,0.014743,...,0.001723,0.027796,0.0,0.026727,0.524666,0.041460,0.394550,0.029031,0.010292,0.599259
1,13593.88256,32879.94646,1.993381,0.262140,0.002066,0.077669,0.000597,0.000977,0.003759,0.099883,...,0.041982,0.021312,0.0,0.015754,0.993900,0.001829,0.000854,0.000586,0.002832,0.699136

In [16]:
# Checking the missing values

missing_df = Training_data.isnull().sum(axis=0).reset_index()
missing_df.columns = ['Column Name', 'Missing Values Count']
missing_df['Filling Factor (%)']=(Training_data.shape[0]-missing_df['Missing Values Count'])/Training_data.shape[0]*100
missing_df.sort_values('Filling Factor (%)').reset_index(drop = True)

             Column Name  Missing Values Count  Filling Factor (%)
0       total_households                     0               100.0
1                 lln_00                     0               100.0
2                 lln_01                     0               100.0
3                 lan_00                     0               100.0
4                 lan_01                     0               100.0
5                 lan_02                     0               100.0
6                 lan_03                     0               100.0
7                 lan_04                     0               100.0
8                 lan_05                     0               100.0
9                 lan_06                     0               100.0
10                lan_07                     0               100.0
11                lan_08                     0               100.0
12                lan_09                     0               100.0
13                lan_10                     0               100.0
14                lan_11                     0               100.0
15                lan_12                     0               100.0
16                lan_13                     0               100.0
17                lan_14                     0               100.0
18                 pg_00                     0               100.0
19                 pg_01                     0               100.0
20                 pg_02                     0               100.0
21                 pg_03                     0               100.0
22                car_01                     0               100.0
23                 pg_04                     0               100.0
24                car_00                     0               100.0
25                stv_00                     0               100.0
26     total_individuals                     0               100.0
27  target_pct_vunerable                     0               100.0
28                 dw_00                     0               100.0
29                 dw_01                     0               100.0
30                 dw_02                     0               100.0
31                 dw_03                     0               100.0
32                 dw_04                     0               100.0
33                 dw_05                     0               100.0
34                 dw_06                     0               100.0
35                 dw_07                     0               100.0
36                 dw_08                     0               100.0
37                 dw_09                     0               100.0
38                 dw_10                     0               100.0
39                 dw_11                     0               100.0
40                 dw_12                     0               100.0
41                 dw_13                     0               100.0
42                psa_00                     0               100.0
43                psa_01                     0               100.0
44                psa_02                     0               100.0
45                psa_03                     0               100.0
46                psa_04                     0               100.0
47                stv_01                     0               100.0
48                lgt_00                     0               100.0

In [17]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn import model_selection

#predicting
array= Training_data.values

X = array[:,1:19]
Y = array[:,19]
Y = Y.astype('int')

#X = array[:,0:8] #0 to 7     ()
#Y = array[:, 8] #target variable / outcome

#split to train, test
#x train and y train will be 70%

from sklearn import model_selection
#0.30 is the testing split percentage, for testing data
X_train, X_test, Y_train, Y_test = model_selection.train_test_split(X,Y, test_size=0.30, random_state=10)


from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.svm import SVC

model = LinearDiscriminantAnalysis()
model.fit(X_train, Y_train) #learning process

#now lets ask the model to predict x test, we hide y test
predictions = model.predict(X_test)
print(predictions)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]

C:\Users\SAMURAI\.conda\envs\TensorFlow\lib\site-packages\sklearn\discriminant_analysis.py:399: RuntimeWarning: invalid value encountered in true_divide
  S**2))[:self._max_components]

In [18]:

print(accuracy_score(Y_test, predictions))        #accuracy_score is imported

1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       953

    accuracy                           1.00       953
   macro avg       1.00      1.00      1.00       953
weighted avg       1.00      1.00      1.00       953

[[953]]

In [19]:
print(classification_report(Y_test, predictions)) #classification report is imported

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       953

    accuracy                           1.00       953
   macro avg       1.00      1.00      1.00       953
weighted avg       1.00      1.00      1.00       953

In [20]:
print(confusion_matrix(Y_test, predictions))      #imported

[[953]]

In [21]:
#new observation
newobservation = model.predict([pd.read_csv('Test_maskedv2.csv')])
print(newobservation)

ValueError: cannot copy sequence with size 1102 to array axis with dimension 49